@baseUrl=http://localhost:3000



###
POST {{baseUrl}}/api/user/register
Content-Type: application/json

{
    "username": "admin3",
    "password": "1234567"
}

###
POST {{baseUrl}}/api/user/login
Content-Type: application/json

{
    "username": "admin3",
    "password": "1234567"
}

###
POST {{baseUrl}}/api/book/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjQ1OTY5MDUsInVzZXJuYW1lIjoiYWRtaW4zIn0.ZwvpjmJDocGrEsda0SuIGqtQPLpwIYd-uxPJSelHENE

{
    "name": "水浒传2",
    "author": "施耐庵",
    "description": "cccccc22",
    "cover": "yx.png"
}


###
GET {{baseUrl}}/api/book/63730


###
GET {{baseUrl}}/api/book/list

###
DELETE {{baseUrl}}/api/book/delete/63730


###
PUT {{baseUrl}}/api/book/update
Content-Type: application/json

{
    "id": 84272,
    "name": "水浒传3",
    "author": "施耐庵",
    "description": "cccccc22",
    "cover": "yx.png"
}


###
POST {{baseUrl}}/api/book/upload
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="aa.png"
Content-Type: binary

------WebKitFormBoundary7MA4YWxkTrZu0gW--
